export const theme = {
  colors: {
    bg: '#F2F3F5',
    surface: '#FFFFFF',
    border: '#D6D9DE',
    text: '#1F2430',
    textMuted: '#6B7280',
    icon: '#4B5563',
    pillBg: '#E7E9ED',
    pillText: '#374151',
    primary: '#636AE8FF',
    primaryDisabled: '#636AE873',
    primaryText: '#FFFFFF',
    primaryTextDisabled: '#FFFFFFB3',
    shadow: 'rgba(0,0,0,0.12)',
    error: '#e53935',
    searchBarBg: '#EFE8F6',
    cardBorder: '#EFE6F4',
    avatarBg: '#E9E0F2',
    cardMeta: '#6E647B',
    skeletonBase: '#EFE8F6',
    skeletonAccent: '#F3ECFA',
    cardSelected: '#E7E9ED',
  },
  radius: {
    xs: 5,
    sm: 6,
    md: 12,
    lg: 14,
    xl: 18,
    full: 999,
  },
  spacing: {
    xxs: 2,
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    horizontalMargin: 14,
  },
  typography: {
    timer: 64,
    title: 22,
    cardTitle: 18,
    searchInput: 16,
    body: 14,
    small: 12,
  },
  elevation: {
    none: 0,
    card: 1,
    surface: 2,
  },
  opacity: {
    disabled: 0.45,
    disabledCard: 0.75,
    dragging: 0.9,
    overlay: 0.92,
  },
  sizes: {
    ctaMinHeight: 48,
    tabHeight: 38,
    searchBarHeight: 30,
    skeletonAvatarSize: 36,
    skeletonLineHeight: 12,
    skeletonLineShortHeight: 10,
    controlBtnMinWidth: 80,
    controlBtnHeight: 36,
  },
  shadows: {
    buttonPrimary: {
      shadowColor: '#636AE8',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 15,
      elevation: 8,
    },
  },
  platform: {
    tabBarHeight: { ios: 84, android: 64 },
    tabBarPaddingBottom: { ios: 24, android: 10 },
    fabBottom: { ios: 34, android: 20 },
  },
} as const;


